# Generated by Django 5.0.6 on 2024-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('teller', 'Bank Teller'), ('loan_officer', 'Loan Officer'), ('credit_card_manager', 'Credit Card Manager'), ('financial_advisor', 'Financial Advisor'), ('admin', 'Admin')], default='customer', max_length=30),
        ),
    ]
